---
# 1. Numpy Exercise
---

Exercise_1 : Numpyライブラリを np というエイリアスでインポートしてください

In [1]:
import numpy as np

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>import numpy as np</code>
</details>

Exercise_2 :  [1, 3, 5, ..., 21, 23] の連続する値を持つ1次元のNumpy Array（変数名 arr1）を作成してください

In [28]:
arr1 = np.arange(1,23.1,2)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1 = np.arange(1, 24, 2)</code>
</details>

In [3]:
# 実行して表示
arr1

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

Exercise_3 : [0., 0.5, 1, ..., 5.5, 6.] （要素数は13）の連続する値を持つ1次元のNumpy Array（変数名 arr2）を作成してください

In [4]:
arr2 = np.linspace(0,6,13)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr2 = np.linspace(0, 6, 13)</code><br>
    <code>np.arange(0, 6.1, 0.5)</code>などでも可
</details>

In [5]:
# 実行して表示
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

Exercise_4 : arr1 を3行4列の配列に変換してください(arr1_reshaped)

In [7]:
arr1.size

12

In [8]:
arr1_reshaped = arr1.reshape(3,4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped = arr1.reshape(3, 4)</code>
</details>

In [9]:
# 実行して表示
arr1_reshaped

array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.],
       [17., 19., 21., 23.]])

Exercise_5: arr1 を2次元で1列の配列に変換してください(arr1_1col)

In [10]:
arr1_1col = arr1.reshape(-1, 1)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1col = arr1.reshape(-1, 1)</code>
</details>

In [11]:
# 実行して表示
arr1_1col

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.],
       [23.]])

Exercise_6 : arr1 を1次元の配列に変換してください(arr1_1dim)。ただし、arr1を扱っていく一方で、arr1_1dimの値の更新を行っていくことを前提とします。（もとのarr1のデータが変更されない手法を用いる）

In [29]:
arr1_1dim = arr1.flatten()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1dim = arr1.flatten()</code>
    <p>※ ravel()の場合はarr1_1dimを更新するとarr1も更新されてしまうため</p>
</details>

In [31]:
# 実行して表示
arr1_1dim

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

Exercise_7 : arr1_reshaped の次元数とその形状を確認してください

In [32]:
# 次元
arr1_reshaped.ndim

2

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.ndim</code>
</details>

In [33]:
# 形状
arr1_reshaped.shape

(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.shape</code>
</details>

Exercise_8: Numpy の random モジュールを使い、0以上1未満の乱数を5つ持つ一次元の配列を作成してください（arr3）

In [34]:
arr3 = np.random.rand(5)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr3 = np.random.rand(5)</code>
</details>

In [35]:
# 実行して表示
arr3

array([0.06706674, 0.56532077, 0.36932201, 0.62057503, 0.71027387])

Exercise_9: 0以上1未満の乱数を持つ2行6列の配列を作成してください（arr4）

In [36]:
arr4 = np.random.rand(2, 6)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr4 = np.random.rand(2, 6)</code>
</details>

In [37]:
# 実行して表示
arr4

array([[0.437408  , 0.87238607, 0.99110488, 0.30433058, 0.8085062 ,
        0.0975935 ],
       [0.59559029, 0.85202833, 0.50330742, 0.76810412, 0.51778299,
        0.90958512]])

Exercise_10 : 平均が 0、標準偏差が 1 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr5）

In [38]:
arr5 = np.random.randn(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr5 = np.random.randn(3, 4)</code>
</details>

In [39]:
# 実行して表示
arr5

array([[-0.34208126,  0.09919507,  0.39148366,  0.61119691],
       [ 1.00432106,  0.62852133, -0.5057471 , -1.68527027],
       [-0.23012536,  0.53684126, -0.0927619 , -0.70052281]])

Exercise_11 : arr5 の全要素での、最大値、最小値、平均を確認してください（max_arr5, min_arr5, mean_arr5）

In [41]:
max_arr5 = arr5.max()
min_arr5 = arr5.min()
mean_arr5 = arr5.mean()
print(f'max : {max_arr5}, min : {min_arr5}, mean : {mean_arr5}')
# 各行ではなく、全体の最大などを取得していることに注意

max : 1.0043210568523815, min : -1.6852702708357052, mean : -0.02374578405178432


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>max_arr5 = arr5.max()</code><br>
    <code>min_arr5 = arr5.min()</code><br>
    <code>mean_arr5 = arr5.mean()</code>
</details>

Exercise_12: 平均が 100、標準偏差が 10 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr6）

In [42]:
arr6 = np.random.normal(100, 10, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr6 = np.random.normal(100, 10, (3, 4))</code>
</details>

In [43]:
# 実行して表示
arr6

array([[106.5281585 , 106.38156004,  96.15640654, 112.31272001],
       [106.63018957,  83.88186451,  91.63743184, 103.24509447],
       [ 90.52743648, 100.66034999, 103.17512136,  98.91459017]])

Exercise_13 : 10 以上 30 未満の値を持つ連続一様分布の3行4列の配列を作成してください （arr7）。また要素全体の平均値が20付近にあることを平均値を求めることで確認してください。

In [44]:
arr7 = np.random.uniform(10, 30, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7 = np.random.uniform(10, 30, (3, 4))</code>
</details>

In [45]:
# 実行して表示
arr7

array([[14.42575505, 20.03967618, 12.42706227, 17.57601613],
       [21.66106037, 22.4712144 , 26.03576814, 25.97755977],
       [25.08016322, 22.95759849, 23.85084141, 13.60210468]])

In [46]:
# 平均値を求める
arr7.mean()
# 20前後の値ならばOK

20.508735008323622

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7.mean()</code>
</details>

Exercise_14 : arr7 の数値をすべて小数第4位で四捨五入した小数3桁の値に変換してください(arr7_3decimal)

In [47]:
arr7_3decimal = np.round(arr7, 3)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_3decimal = np.round(arr7, 3)</code>
</details>

In [48]:
# 実行して表示
arr7_3decimal

array([[14.426, 20.04 , 12.427, 17.576],
       [21.661, 22.471, 26.036, 25.978],
       [25.08 , 22.958, 23.851, 13.602]])

Exercise_15: リスト lis の文字をランダムに10個持つ1次元の配列を作成し（arr8）、データタイプを object に変更してください

In [49]:
# リストを作成
lis = list('GOOD!')   # ['G', 'O', 'O', 'D', '!']
arr8 = np.random.choice(lis, 10)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = np.random.choice(lis, 10)</code>
</details>

In [50]:
# 実行して表示
arr8

array(['O', 'G', 'O', '!', 'O', 'O', 'G', 'D', 'G', '!'], dtype='<U1')

In [51]:
# データタイプを変更
arr8 = arr8.astype(object)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = arr8.astype(object)</code>
</details>

In [52]:
# 実行して表示
arr8

array(['O', 'G', 'O', '!', 'O', 'O', 'G', 'D', 'G', '!'], dtype=object)

Exercise_16 : 次のarr9のデータタイプが 'int32' であることを確認し、その後データタイプを 'float' に変更してください

In [53]:
# dtypeの確認
arr9 = np.array([1, 3, 5, 7, 9]) 
arr9.dtype

dtype('int64')

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.dtype</code>
</details>

In [54]:
# floatに変更
arr9 = arr9.astype(float)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.astype(float)</code><br>
</details>

In [55]:
# 実行して表示
arr9

array([1., 3., 5., 7., 9.])

Exercise_17 : 配列arr10の分散と標準偏差を「計算して」求めてください。また、メソッドを用いてその値が正しいことを確認してください。

In [56]:
# 実行して表示
np.random.seed(17)
arr10 = np.random.randint(0, 10, 5)
arr10

array([1, 6, 6, 9, 0])

In [57]:
# 実行して表示
mean = arr10.mean()
mean

4.4

In [58]:
total = 0
for i in arr10:
    total += i
total

22

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>total += (i - mean)**2</code><br>
</details>

In [59]:
variance = ((arr10 - mean)**2).sum()/len(arr10)
# 実行して表示
variance

11.440000000000001

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>variance = total / len(arr10)</code><br>
</details>

In [60]:
standard_deviation = np.sqrt(variance)
# 実行して表示
standard_deviation

3.3823069050575527

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>standard_deviation = np.sqrt(variance)</code><br>
</details>

In [61]:
# メソッドを使って分散を求める
arr10.var()

11.440000000000001

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.var()</code><br>
</details>

In [62]:
# メソッドを使って標準偏差を求める
arr10.std()

3.3823069050575527

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.std()</code><br>
</details>

## 以上